'use client'
import Navbar from '@/components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import { ReduxProvider } from './store/provider';

import { Provider } from 'react-redux';
import store from './store';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
            <Navbar />
            {children}
            </Provider>
      </body>
    </html>
  );
}

